#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

depends() {
    # Flatcar: do not depend on "url-lib network"
    echo qemu systemd
}

install_ignition_unit() {
    local unit="$1"; shift
    local target="${1:-ignition-complete.target}"; shift
    local instantiated="${1:-$unit}"; shift
    inst_simple "$moddir/$unit" "$systemdsystemunitdir/$unit"
    mkdir -p "$initdir/$systemdsystemunitdir/$target.requires"
    ln -sfn "../$unit" "$initdir/$systemdsystemunitdir/$target.requires/$instantiated"
}

install() {
    # Flatcar: add coreos-metadata, systemd-detect-virt, mountpoint, nvme
    inst_multiple \
        basename \
        lsblk

    # Not all features of the configuration may be available on all systems
    # (e.g. on embedded systems), so only add applications which are actually
    # present
    inst_multiple -o \
        groupadd \
        groupdel \
        systemd-detect-virt \
        mountpoint \
        mkfs.btrfs \
        mkfs.ext4 \
        mkfs.fat \
        mkfs.xfs \
        mkswap \
        nvme \
        sgdisk \
        partx \
        useradd \
        userdel \
        usermod \
        wipefs \
        cryptsetup

    # Flatcar: add cloud_aws_ebs_nvme_id
    inst_script "$udevdir/cloud_aws_ebs_nvme_id" \
        "/usr/lib/udev/cloud_aws_ebs_nvme_id"

    # Needed for clevis binding; note all binaries related to unlocking are
    # included by the Clevis dracut modules.
    inst_multiple -o \
        clevis-encrypt-sss \
        clevis-encrypt-tang \
        clevis-encrypt-tpm2 \
        clevis-luks-bind \
        clevis-luks-common-functions \
        clevis-luks-unlock \
        pwmake \
        sort \
        tail \
        tpm2_create

    # Required by s390x's z/VM installation.
    # Supporting https://github.com/coreos/ignition/pull/865
    inst_multiple -o chccwdev vmur

    # Required on system using SELinux
    inst_multiple -o setfiles

    inst_script "$moddir/ignition-kargs-helper" \
        "/usr/sbin/ignition-kargs-helper"

    # Flatcar: add ignition-setup-pre
    inst_script "$moddir/ignition-setup-pre.sh" \
        "/usr/sbin/ignition-setup-pre"

    # Rule to allow udev to discover unformatted encrypted devices
    inst_simple "$moddir/99-xx-ignition-systemd-cryptsetup.rules" \
        "/usr/lib/udev/rules.d/99-xx-ignition-systemd-cryptsetup.rules"

    # disable dictcheck
    inst_simple "$moddir/ignition-luks.conf" \
        "/etc/security/pwquality.conf.d/ignition-luks.conf"

    # Ignition calls is-live-image.
    inst_script "$moddir/is-live-image.sh" \
        /bin/is-live-image

    inst_simple "$moddir/ignition-generator" \
        "$systemdutildir/system-generators/ignition-generator"

    local x
    for x in "complete" "subsequent" "diskful" "diskful-subsequent"; do
        inst_simple "$moddir/ignition-$x.target" \
            "$systemdsystemunitdir/ignition-$x.target"
    done

    # Flatcar: add ignition-quench.service, boot.mount,
    # flatcar-afterburn-network.service, flatcar-static-network.service,
    # flatcar-metadata-hostname.service, flatcar-openstack-hostname.service
    inst_simple "$moddir/ignition-quench.service" \
        "$systemdsystemunitdir/ignition-quench.service"
    inst_simple "$moddir/boot.mount" \
        "$systemdsystemunitdir/boot.mount"
    inst_simple "$moddir/flatcar-afterburn-network.service" \
        "$systemdsystemunitdir/flatcar-afterburn-network.service"
    inst_simple "$moddir/flatcar-static-network.service" \
        "$systemdsystemunitdir/flatcar-static-network.service"
    inst_simple "$moddir/flatcar-metadata-hostname.service" \
        "$systemdsystemunitdir/flatcar-metadata-hostname.service"
    inst_simple "$moddir/flatcar-openstack-hostname.service" \
        "$systemdsystemunitdir/flatcar-openstack-hostname.service"

    install_ignition_unit ignition-fetch.service
    install_ignition_unit ignition-fetch-offline.service
    install_ignition_unit ignition-kargs.service
    install_ignition_unit ignition-disks.service
    install_ignition_unit ignition-mount.service
    install_ignition_unit ignition-files.service

    # units only started when we have a boot disk
    # path generated by systemd-escape --path /dev/disk/by-label/root
    install_ignition_unit ignition-remount-sysroot.service ignition-diskful.target

    # needed for openstack config drive support
    # Flatcar: add 66-azure-storage.rules and 90-cloud-storage.rules
    inst_rules 60-cdrom_id.rules 66-azure-storage.rules 90-cloud-storage.rules

    # Flatcar: add symlinks for dependencies of Ignition, coreos-metadata (afterburn), and
    # Clevis. This saves space in the initramfs image by replacing files with symlinks to
    # the previously mounted /sysusr/.
    local executable
    for executable in "${dracutsysrootdir}"{\
/usr/bin/clevis*,\
/usr/bin/coreos-metadata,\
/usr/bin/curl,\
/usr/bin/ignition,\
/usr/bin/jose,\
/usr/bin/luksmeta,\
/usr/bin/tpm2,\
/usr/bin/xfs_db,\
/usr/bin/xfs_repair,\
/usr/lib/systemd/systemd-reply-password,\
/usr/libexec/clevis*\
}; do
        if [[ ! -f ${executable} ]]; then
            dfatal "Cannot create wrapper for ${executable} because it is not found"
            exit 1
        elif [[ ! -x ${executable} ]]; then
            continue
        fi

        local wrapper="${DRACUT_TMPDIR}/${executable##*/}-wrapper"
        cat <<EOF > "${wrapper}"
#!/bin/sh
LD_LIBRARY_PATH=/sysusr/usr/lib64 exec "/sysusr${executable#"$dracutsysrootdir"}" "\$@"
EOF
        chmod +x "${wrapper}"
        inst_script "${wrapper}" "${executable#"$dracutsysrootdir"}"
        rm "${wrapper}"
    done

    # Ignition reads user.ign and base.d/* in /usr/lib/ignition by default, but
    # our initrd is not writeable. Create symlinks pointing to /oem in advance.
    mkdir -m0755 -p "${initdir}"/usr/lib/ignition
    ln -snf /oem/config.ign "${initdir}"/usr/lib/ignition/user.ign
    ln -snf /oem/base/ "${initdir}"/usr/lib/ignition/base.d
}

# See: https://github.com/coreos/ignition/commit/d304850c3d3696822bc05e0833ee4b27df9d7a38
installkernel() {
     # required by hyperv platform to read kvp from the kernel
     instmods -c hv_utils
}
